components:
  schemas:
    book:
      type: object
      properties:
        code:
          type: string
          example: "NRN-7"
        title:
          type: string
          example: "The Lion, the Witch and the Wardrobe"
        author:
          type: string
          example: "C.S. Lewis"
        stock:
          type: integer
          example: "3"
    member:
      type: object
      properties:
        code:
          type: string
          example: "M004"
        name:
          type: string
          example: "Juki"
        penalty:
          type: string
          format: date
    borrow:
      type: object
      properties:
        book_code:
          type: string
          example: "NRN-7"
        member_code:
          type: string
          example: "M004"
        date_borrow:
          type: string
          format: date
